# Generated by Django 4.0.5 on 2022-07-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0003_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentsa',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentsq',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
