# Generated by Django 4.0.5 on 2022-07-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0005_question_ans_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans_verified',
            new_name='verified_answer',
        ),
    ]
