# Generated by Django 4.0.5 on 2022-08-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0008_remove_user_img_remove_user_title_delete_commentsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
